# Generated by Django 6.0 on 2025-12-12 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The 1st of the month this slip belongs to')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('present_days', models.IntegerField()),
                ('total_working_days', models.IntegerField(default=30)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('GEN', 'Generated'), ('PD', 'Paid'), ('HLD', 'Held (Compliance Issue)')], default='GEN', max_length=3)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
