# Generated by Django 6.0 on 2025-12-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='salary_slips/'),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='status',
            field=models.CharField(choices=[('GEN', 'Generated'), ('PAID', 'Paid')], default='GEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='total_working_days',
            field=models.IntegerField(),
        ),
    ]
