# Generated by Django 6.0 on 2025-12-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='General', help_text='The Department this user belongs to (e.g. IT, HR, Sales)', max_length=50),
        ),
    ]
