# Generated by Django 6.0 on 2025-12-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_user_department'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
