# Generated by Django 6.0 on 2025-12-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('form_schema', models.JSONField(default=list, help_text='The structure of the form questions')),
                ('target_department', models.CharField(blank=True, help_text="Leave empty for Open to All. Set 'IT' to restrict to IT dept.", max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_viewers', models.ManyToManyField(blank=True, help_text='Specific users who are allowed to view the responses for this program.', related_name='viewable_programs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='SUBMITTED', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_applications', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.programme')),
            ],
            options={
                'unique_together': {('programme', 'applicant')},
            },
        ),
    ]
