"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url
from dotenv import load_dotenv  # Load .env variables

# 1. Define BASE_DIR first (So we know where the root is)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Initialize Environment Variables
env = environ.Env()

# 3. FORCE read from the root .env file
# This fixes the "ImproperlyConfigured" error
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# --- DYNAMIC SECURITY CONFIGURATION ---
# Now it reads from the file. If file is missing, it crashes (good for safety).
SECRET_KEY = env('SECRET_KEY')

# Cast the DEBUG value to a boolean (True/False)
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'apps.identity.apps.IdentityConfig',
    'apps.hr.apps.HrConfig',
    'apps.operations.apps.OperationsConfig',
    'apps.finance.apps.FinanceConfig',
    'rest_framework_simplejwt.token_blacklist',
    'apps.canteen.apps.CanteenConfig',
    'apps.programs.apps.ProgramsConfig',
]

# --- DATABASE CONFIGURATION ---
# If DATABASE_URL exists (Production/Env), use it. Else use SQLite (Local Fallback).
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}

# --- AWS CONFIGURATION ---
# This makes AWS keys available globally in the project
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_REGION = env('AWS_REGION', default='ap-south-1')

# settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # --- THROTTLING CONFIGURATION ---
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # For Login page
        'rest_framework.throttling.UserRateThrottle'  # For logged-in users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',       # prevent brute-force login
        'user': '1000/day',       # standard user limit
        'burst': '60/minute',     # limit rapid-fire requests
    }
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=["http://localhost:3000"])

#CORS_ALLOW_ALL_ORIGINS = True  #(ONLY IF NEEDED FOR TESTING)

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=["http://localhost:3000"])

# If True, cookies are only sent over HTTPS. (Essential for Prod, disable for Local)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=False)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # WhiteNoise collects here

# Enable WhiteNoise storage
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
AUTH_USER_MODEL = 'identity.User'
import os

# Base url to serve media files
MEDIA_URL = '/media/'

# Path where media is stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- EMAIL SETTINGS ---
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@smg.com')

# --- AWS S3 SETTINGS ---
if os.getenv('AWS_ACCESS_KEY_ID'):
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    # Static & Media Storage Logic
    AWS_S3_FILE_OVERWRITE = False  # UUIDs handle uniqueness, don't overwrite
    AWS_DEFAULT_ACL = None
    AWS_S3_VERIFY = True

    # Django 4.2+ Storage Configuration
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": "media", # Files go to bucket/media/
                "default_acl": "public-read", # Optional: allows direct link access
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    # This URL is how the frontend will access images
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/'
else:
    # Local Fallback
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# =========================================================
# CELERY CONFIGURATION (Asynchronous Tasks)
# =========================================================
# The Broker: Where Django sends messages (Redis)
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')

# The Result Backend: Where Celery stores "It's done!" (Redis)
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/0')

# Timezone settings
CELERY_TIMEZONE = 'Asia/Kolkata' # Or 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max per task

# =========================================================
# PRODUCTION SECURITY SETTINGS
# =========================================================
if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = True
    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Prevent browser from guessing content types
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Protect against XSS
    SECURE_BROWSER_XSS_FILTER = True
    # Protect against Clickjacking (embedding in iframes)
    X_FRAME_OPTIONS = 'DENY'

# =========================================================
# If we are running 'test', disable real Celery/Redis connection
import sys
if 'test' in sys.argv:
    # 1. Run Celery tasks immediately in memory (No Redis)
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    
    # 2. Use Dummy Cache (No Redis)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
    
    # 3. Throttling Configuration
    # We cannot empty this because custom classes (like BurstRateThrottle)
    # explicitly look for keys like 'burst' or 'sustained'.
    # We set them to '10000/second' to effectively disable the limit.
    if 'REST_FRAMEWORK' not in locals():
        REST_FRAMEWORK = {}
        
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        'burst': '10000/sec',
        'sustained': '10000/sec',
        'anon': '10000/sec',
        'user': '10000/sec',
    }