# Generated by Django 6.0 on 2025-12-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='monthly_stipend',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=10),
        ),
    ]
