# Generated by Django 6.0 on 2025-12-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_internprofile_monthly_stipend'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
